"""Tests for the Showdown renderer.

The renderer is a pure function — golden-file comparison covers it
exhaustively.

The golden assertions matter because the in-sheet `TEAMDATAFROMPASTE`
AppsScript depends on this format being parseable: any drift here would
silently break the species columns for every replica-added team. The
canonical-output reference is the wyatt_team.pokepaste.txt generated by
the user's standalone build_pokepaste.py — the format that's already
known to round-trip cleanly through both pokepast.es and the AppsScript.
"""

from __future__ import annotations

from sketch.showdown.renderer import render_showdown
from sketch.team import PokemonEntry, TeamData

# CRLF separator the renderer emits. Kept local to the test rather than
# importing the private `_LINE_END` from the renderer so this suite
# asserts the contract (the rendered output uses CRLF) rather than
# testing implementation detail (the specific constant name).
_CRLF = "\r\n"


def _entry(
    *,
    species: str = "Floette-Eternal",
    gender: str | None = "F",
    item: str | None = "Floettite",
    ability: str = "Flower Veil",
    nature: str = "Modest",
    evs: dict | None = None,
    moves: list[str] | None = None,
) -> PokemonEntry:
    return PokemonEntry(
        species=species,
        gender=gender,
        item=item,
        ability=ability,
        nature=nature,
        evs=evs or {"hp": 32, "atk": 0, "def": 0, "spa": 32, "spd": 0, "spe": 2},
        moves=moves or ["Dazzling Gleam", "Moonblast", "Light of Ruin", "Protect"],
    )


class TestRenderShowdown:
    def test_floette_matches_reference_block(self):
        # Golden against the canonical Showdown-export shape. CRLF line
        # endings are load-bearing — pokepast.es's block-splitter only
        # recognizes `\r\n\r\n` as the Pokemon separator (Showdown's
        # clipboard export uses CRLF, and pokepast.es matches that).
        team = TeamData(pokemon=[_entry()])
        expected = _CRLF.join(
            [
                "Floette-Eternal (F) @ Floettite",
                "Ability: Flower Veil",
                "EVs: 32 HP / 32 SpA / 2 Spe",
                "Modest Nature",
                "- Dazzling Gleam",
                "- Moonblast",
                "- Light of Ruin",
                "- Protect",
            ]
        )
        assert render_showdown(team) == expected

    def test_male_gender_renders_with_M_suffix(self):
        team = TeamData(pokemon=[_entry(gender="M")])
        first_line = render_showdown(team).splitlines()[0]
        assert first_line == "Floette-Eternal (M) @ Floettite"

    def test_genderless_omits_paren_suffix(self):
        # Genderless mons (Magnemite, Klefki, etc.) shouldn't get an empty
        # "()" — the suffix is omitted entirely.
        team = TeamData(pokemon=[_entry(gender=None)])
        first_line = render_showdown(team).splitlines()[0]
        assert first_line == "Floette-Eternal @ Floettite"
        assert "()" not in first_line

    def test_no_item_omits_at_suffix(self):
        team = TeamData(pokemon=[_entry(item=None)])
        first_line = render_showdown(team).splitlines()[0]
        assert first_line == "Floette-Eternal (F)"
        assert " @ " not in first_line

    def test_no_item_and_no_gender(self):
        team = TeamData(pokemon=[_entry(gender=None, item=None)])
        first_line = render_showdown(team).splitlines()[0]
        assert first_line == "Floette-Eternal"

    def test_zero_ev_stats_are_omitted_from_evs_line(self):
        team = TeamData(
            pokemon=[
                _entry(
                    evs={
                        "hp": 32,
                        "atk": 0,
                        "def": 0,
                        "spa": 32,
                        "spd": 0,
                        "spe": 2,
                    }
                )
            ]
        )
        rendered = render_showdown(team)
        assert "EVs: 32 HP / 32 SpA / 2 Spe" in rendered
        # The "0" cells (Atk, Def, SpD) should not appear in the EVs line.
        assert "0 Atk" not in rendered
        assert "0 Def" not in rendered
        assert "0 SpD" not in rendered

    def test_full_zero_ev_team_skips_evs_line(self):
        team = TeamData(
            pokemon=[
                _entry(evs={"hp": 0, "atk": 0, "def": 0, "spa": 0, "spd": 0, "spe": 0})
            ]
        )
        rendered = render_showdown(team)
        assert "EVs:" not in rendered

    def test_does_not_emit_level_line(self):
        # Champions Replica share screen doesn't surface level, and the
        # reference paste omits it. The renderer must NOT emit "Level: 50"
        # — that would diverge from the AppsScript's expected shape.
        team = TeamData(pokemon=[_entry()])
        rendered = render_showdown(team)
        assert "Level:" not in rendered

    def test_does_not_emit_tera_type_line(self):
        # Same as Level — share screen doesn't capture it, reference paste
        # omits it, renderer must not emit it.
        team = TeamData(pokemon=[_entry()])
        rendered = render_showdown(team)
        assert "Tera Type:" not in rendered

    def test_does_not_emit_ivs_line(self):
        team = TeamData(pokemon=[_entry()])
        rendered = render_showdown(team)
        assert "IVs:" not in rendered

    def test_six_mons_separated_by_crlf_blank_lines(self):
        # The Pokemon separator is `\r\n\r\n` (CRLF blank line), not
        # `\n\n`. pokepast.es's block-splitter requires CRLF to identify
        # Pokemon boundaries; emitting LF only collapses the whole
        # paste into one big block on render.
        team = TeamData(pokemon=[_entry() for _ in range(6)])
        rendered = render_showdown(team)
        blocks = rendered.split(_CRLF * 2)
        assert len(blocks) == 6

    def test_no_trailing_newline(self):
        team = TeamData(pokemon=[_entry()])
        assert not render_showdown(team).endswith("\n")

    def test_nature_line_uses_resolved_name(self):
        # The Pokemon dataclass carries the already-resolved name. The
        # renderer just emits it — no double-resolution.
        team = TeamData(pokemon=[_entry(nature="Adamant")])
        assert "Adamant Nature" in render_showdown(team)
