"""Tests for the Showdown renderer and pokepast.es uploader.

The renderer is a pure function — golden-file comparison covers it
exhaustively. The uploader is mocked with `aioresponses` so the suite
never makes a real POST.

The golden assertions matter because the in-sheet `TEAMDATAFROMPASTE`
AppsScript depends on this format being parseable: any drift here would
silently break the species columns for every replica-added team. The
canonical-output reference is the wyatt_team.pokepaste.txt generated by
the user's standalone build_pokepaste.py — the format that's already
known to round-trip cleanly through both pokepast.es and the AppsScript.
"""

from __future__ import annotations

import pytest
from aioresponses import aioresponses

from sketch.replica.extractor import PokemonEntry, TeamData
from sketch.replica.pokepaste_renderer import (
    RenderError,
    post_to_pokepaste,
    render_showdown,
)


def _entry(
    *,
    species: str = "Floette",
    gender: str | None = "F",
    item: str | None = "Floettite",
    ability: str = "Flower Veil",
    nature: str = "Modest",
    evs: dict | None = None,
    moves: list[str] | None = None,
) -> PokemonEntry:
    return PokemonEntry(
        species=species,
        gender=gender,
        item=item,
        ability=ability,
        nature=nature,
        evs=evs or {"hp": 32, "atk": 0, "def": 0, "spa": 32, "spd": 0, "spe": 2},
        moves=moves or ["Dazzling Gleam", "Moonblast", "Light of Ruin", "Protect"],
    )


class TestRenderShowdown:
    def test_floette_matches_reference_block(self):
        # Golden against the first block of wyatt_team.pokepaste.txt — the
        # canonical shape the AppsScript parses against.
        team = TeamData(pokemon=[_entry()])
        expected = "\n".join(
            [
                "Floette (F) @ Floettite",
                "Ability: Flower Veil",
                "EVs: 32 HP / 32 SpA / 2 Spe",
                "Modest Nature",
                "- Dazzling Gleam",
                "- Moonblast",
                "- Light of Ruin",
                "- Protect",
            ]
        )
        assert render_showdown(team) == expected

    def test_male_gender_renders_with_M_suffix(self):
        team = TeamData(pokemon=[_entry(gender="M")])
        assert render_showdown(team).splitlines()[0] == "Floette (M) @ Floettite"

    def test_genderless_omits_paren_suffix(self):
        # Genderless mons (Magnemite, Klefki, etc.) shouldn't get an empty
        # "()" — the suffix is omitted entirely.
        team = TeamData(pokemon=[_entry(gender=None)])
        first_line = render_showdown(team).splitlines()[0]
        assert first_line == "Floette @ Floettite"
        assert "()" not in first_line

    def test_no_item_omits_at_suffix(self):
        team = TeamData(pokemon=[_entry(item=None)])
        first_line = render_showdown(team).splitlines()[0]
        assert first_line == "Floette (F)"
        assert " @ " not in first_line

    def test_no_item_and_no_gender(self):
        team = TeamData(pokemon=[_entry(gender=None, item=None)])
        first_line = render_showdown(team).splitlines()[0]
        assert first_line == "Floette"

    def test_zero_ev_stats_are_omitted_from_evs_line(self):
        team = TeamData(
            pokemon=[
                _entry(
                    evs={
                        "hp": 32,
                        "atk": 0,
                        "def": 0,
                        "spa": 32,
                        "spd": 0,
                        "spe": 2,
                    }
                )
            ]
        )
        rendered = render_showdown(team)
        assert "EVs: 32 HP / 32 SpA / 2 Spe" in rendered
        # The "0" cells (Atk, Def, SpD) should not appear in the EVs line.
        assert "0 Atk" not in rendered
        assert "0 Def" not in rendered
        assert "0 SpD" not in rendered

    def test_full_zero_ev_team_skips_evs_line(self):
        team = TeamData(
            pokemon=[
                _entry(evs={"hp": 0, "atk": 0, "def": 0, "spa": 0, "spd": 0, "spe": 0})
            ]
        )
        rendered = render_showdown(team)
        assert "EVs:" not in rendered

    def test_does_not_emit_level_line(self):
        # Champions Replica share screen doesn't surface level, and the
        # reference paste omits it. The renderer must NOT emit "Level: 50"
        # — that would diverge from the AppsScript's expected shape.
        team = TeamData(pokemon=[_entry()])
        rendered = render_showdown(team)
        assert "Level:" not in rendered

    def test_does_not_emit_tera_type_line(self):
        # Same as Level — share screen doesn't capture it, reference paste
        # omits it, renderer must not emit it.
        team = TeamData(pokemon=[_entry()])
        rendered = render_showdown(team)
        assert "Tera Type:" not in rendered

    def test_does_not_emit_ivs_line(self):
        team = TeamData(pokemon=[_entry()])
        rendered = render_showdown(team)
        assert "IVs:" not in rendered

    def test_six_mons_separated_by_blank_lines(self):
        team = TeamData(pokemon=[_entry() for _ in range(6)])
        rendered = render_showdown(team)
        blocks = rendered.split("\n\n")
        assert len(blocks) == 6

    def test_no_trailing_newline(self):
        team = TeamData(pokemon=[_entry()])
        assert not render_showdown(team).endswith("\n")

    def test_nature_line_uses_resolved_name(self):
        # The Pokemon dataclass carries the already-resolved name. The
        # renderer just emits it — no double-resolution.
        team = TeamData(pokemon=[_entry(nature="Adamant")])
        assert "Adamant Nature" in render_showdown(team)


class TestPostToPokepaste:
    async def test_returns_canonical_url_from_json_response(self):
        # /create.json returns {"id", "url", "title", "author"} — we read
        # `url` directly and canonicalize it for dedup-shape consistency.
        with aioresponses() as mock:
            mock.post(
                "https://pokepast.es/create.json",
                status=200,
                payload={
                    "id": "abc123def",
                    "url": "https://pokepast.es/abc123def",
                    "title": "Replica QBXXWXL05U",
                    "author": "",
                },
            )
            url = await post_to_pokepaste("paste text", "Replica QBXXWXL05U")
        assert url == "https://pokepast.es/abc123def"

    async def test_canonicalizes_returned_url(self):
        # Server might respond with http or trailing slash — the
        # canonicalizer collapses to the dedup form.
        with aioresponses() as mock:
            mock.post(
                "https://pokepast.es/create.json",
                status=200,
                payload={
                    "id": "xyz789",
                    "url": "http://pokepast.es/xyz789/",
                },
            )
            url = await post_to_pokepaste("paste text", "Replica BBBB222233")
        assert url == "https://pokepast.es/xyz789"

    async def test_4xx_status_raises_render_error(self):
        with aioresponses() as mock:
            mock.post(
                "https://pokepast.es/create.json",
                status=400,
                body="Bad Request",
            )
            with pytest.raises(RenderError, match="pokepast.es"):
                await post_to_pokepaste("paste text", "Replica CCCC333344")

    async def test_5xx_status_raises_render_error(self):
        with aioresponses() as mock:
            mock.post(
                "https://pokepast.es/create.json",
                status=500,
                body="Internal Server Error",
            )
            with pytest.raises(RenderError, match="pokepast.es"):
                await post_to_pokepaste("paste text", "Replica DDDD444455")

    async def test_non_json_body_raises_render_error(self):
        # A 200 with an HTML body (e.g. cloudflare interstitial) — the
        # uploader must catch the parse failure rather than crash on the
        # downstream key access.
        with aioresponses() as mock:
            mock.post(
                "https://pokepast.es/create.json",
                status=200,
                body="<html>not json</html>",
            )
            with pytest.raises(RenderError, match="pokepast.es"):
                await post_to_pokepaste("paste text", "Replica EEEE555566")

    async def test_missing_url_field_raises(self):
        # JSON response but missing the `url` field — defensive against
        # an API shape change.
        with aioresponses() as mock:
            mock.post(
                "https://pokepast.es/create.json",
                status=200,
                payload={"id": "abc123"},
            )
            with pytest.raises(RenderError, match="pokepast.es"):
                await post_to_pokepaste("paste text", "Replica FFFF666677")
